### ISSUE TITLE
概要が字下げされない

### ISSUE THREAD

**Issue by defaultcf** [2017pro02/interim-report-medical#1]
subfilesのせいかと思ったら、関係無い。分からん。

**Comment by itoukei** [comment]
TeX的な話かな?! そもそもどうなると正解かってのもあるけど、TeXにどう書いてて、現状どうなってるのかも書いといた方が、サポートしてもらいやすそうだけど...

**Comment by a5ob7r** [comment]
ちょっと調べてみたけど，`funpro.sty`をいじればとりあえずは行けそう．
252行目辺りから
```tex
\newenvironment{jabstract}{%
   \centerline{\Large\headfont 概要}\par%
   \begin{list}{}{%
      \leftmargin=3zw
      \rightmargin\leftmargin
      \itemindent1zw % 追加
      \listparindent1zw}\item[]\relax % 値を0ptから1zwに変更
      \small\widebaselines}%
   {\end{list}\par\clearpage}
```
ってすれば一先ずは・・・

恵先生も言ってるけど，概要ってどんな感じが正解なのかな?
もっといいやり方があるかもしれない・・・

参考資料
[http://www.biwako.shiga-u.ac.jp/sensei/kumazawa/tex/list.html](http://www.biwako.shiga-u.ac.jp/sensei/kumazawa/tex/list.html)
※概要だから`abstract`だと思ったら`list`だったっていう・・・

**Comment by taku-okuno** [comment]
（工学系の?）論文では、概要（アブストラクト）は段落分けしないのが一般的なので、そうなっているのかも。
http://www.okada-lab.org/Ronbun/Structure/AbstIntroConcl.php

**Comment by defaultcf** [comment]
メモ程度に書き留めたissueで申し訳ありませんでした。

皆様、ご助言頂きありがとうございます。
@AoiSato の通りにすると字下げを行うことが出来ました。

しかし概要の段落分け自体行わないというお話もありますので、一度SlackのGeneralで訊いてから判断することに致します。

**Comment by defaultcf** [comment]
去年の中間報告書は、3班とも概要は改行あり字下げありで書かれていたので、今年もそうなるものかと思っていました...

**Comment by defaultcf** [comment]
段落分けせず、字下げもしないということで決着がつきました。
