### ISSUE TITLE
PDF生成時にエラーが出る

### ISSUE THREAD

**Issue by defaultcf** [2017pro02/interim-report-medical#7]
`feature/aya`でエラーが出るようになったらしい。
私が対応します。

**Comment by Ayarai** [comment]
解決した🙆

**Comment by a5ob7r** [comment]
何が問題だったとかどうやって解決したとかがわかるなら，共有も兼ねて残してもらえるとうれしいです．

**Comment by Ayarai** [comment]
自分のPC側の問題でした。自分のPCの場合、新しいstyファイル(funpro.sty、url.styなど)は報告書のファイルに置いてありました。しかしどうやらC:\w32tex\share\texmf-local\tex\platex 以下にないと、tex実行時に"not found"というエラーが出てくるみたいで、手動でstyファイルを上記の場所移動したらエラーが消えました...🙇‍♀️

**Comment by a5ob7r** [comment]
本人の環境を見せてもらったところ，どうやら`report.tex`以外のファイルをコンパイルしようとするとエラーが出ているようでした．以前は`sections`以下のtexファイルを単体でコンパイルするとエラー無しでセクションごとのPDF生成ができていたようですが，画像を挿入しようとするとなにやらエラーが発生するようになっていたようです．その問題についての解決は保留としましたが，ひとまずは`report.tex`をコンパイルするようにすることで報告書全体のPDF生成ができないという問題については解決しました．
